[tool:pytest]
addopts = 
    --verbose
    --tb=short
    --cov=../
    --cov-report=term-missing
    --cov-report=html:htmlcov
    --cov-fail-under=80
    --durations=5

testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

# Coverage configuration
[coverage:run]
source = ../
omit = 
    */test_*
    */__pycache__/*
    */Testing/*
    */.env
    */venv/*

branch = True

[coverage:report]
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.:
    def __repr__
    raise NotImplementedError

ignore_errors = True